### ISSUE TITLE
Inputting text into the chat can cause page scroll

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#3110]
### Share your bug report, feature request, or comment.

How to replicate -

From a refresh, scroll the page slightly so the video isn't at the top of the screen, type in the chatbox - the page will jump around

I made a short screencast showing the issue (attaching), with an overlay showing my mouse clicks/scrolls and key presses

https://github.com/owncast/owncast/assets/4265148/4ccf347e-d409-475c-879f-2a080f5ca021

**Comment by gabek** [comment]
I'm assuming this is similar to #2955, but I've only ever seen that on an iPad. I've never seen this happen on a desktop browser until now. I've yet to be able to track this down for the iPad. What environment is this on?

**Comment by jprjr** [comment]
In my case, Linux (XFCE Desktop environment) with Google Chrome and Firefox. I'm getting the same thing reported by Chrome/Firefox users on Windows as well.

**Comment by jprjr** [comment]
This may have been fixed by https://github.com/owncast/owncast/commit/ad814a8802c7ce4767e23dabbe8f67c18d64a727

I pulled down version 0.1.0 and ran locally and could create the issue. I checked out https://github.com/owncast/owncast/commit/683f73c379c4cb58bcb630babe09ad7a9e1a1a8f (the parent commit of https://github.com/owncast/owncast/commit/ad814a8802c7ce4767e23dabbe8f67c18d64a727) - and could create the issue.

I checked out https://github.com/owncast/owncast/commit/ad814a8802c7ce4767e23dabbe8f67c18d64a727 - and I can't recreate the issue. Same for the latest commit on develop.

I'm suspecting slatejs may have been the culprit?

**Comment by gabek** [comment]
~~It shouldn't be related, especially if making changes to the messages container fixes it. But you never know.~~

Sorry, I thought I was looking at #3109. Ignore that response.

I'll do some testing across devices and browsers after making that chat input change, that would make sense that it could be to blame.

**Comment by gabek** [comment]
Still occurring on iPad. https://github.com/owncast/owncast/assets/414923/3d3c8da0-9e3d-4ca9-8614-443d33559672

**Comment by gabek** [comment]
I'll close this and keep the iPad specific issue open, since they seem to not be related after all. Thanks for testing and reporting back!
