### ISSUE TITLE
FireFox Owncast Admin Not Loading

### ISSUE THREAD

**Issue by 2TonWaffle** [owncast/owncast#3220]
### Share your bug report, feature request, or comment.

Server is at 0.1.1 and trying to load into the admin within FireFox and it's stuck in a forever non-loading state. I'm able to get into the admin side of the server no problem within a chrome base browser but, not FireFox. Also noticing that # is being added to the end of the url indiebasement.live/#

![61C6A275-9C22-4A15-9D9D-FF0F3C633DEE](https://github.com/owncast/owncast/assets/128096662/b4de27ef-d14e-4570-9b9c-f06f123b6db6)

**Comment by gabek** [comment]
As a sanity check I just tested with Firefox and it seems ok. Did it work for you with v0.1.0? If so, could you try clearing your browser cache? I wonder if it's trying to load old resources that are updated with the new version, or loading half from cache and half from the server creating issues?

Can you try it in a private browsing tab? Is there any browser extension that might be impacting things?

I'm just guessing at possible ideas, though.

**Comment by 2TonWaffle** [comment]
Cleared data and the cache still resulted in no admin loading but was able to get into it on a new incognito tab though. I only use Bitwarden, Ublock Origin, BetterTTV for extensions and I've turned off Ublock with no change. I'll try with no extensions installed.

>

**Comment by 2TonWaffle** [comment]
Seems like everything is working now. Have cleared data after installing each extension on its own and trying the admin login. Works fine now.

**Comment by CaptainCalliope** [comment]
I'm having this same problem. I've fixed it before and I'm pretty sure it's an extension issue, but I haven't identified which one yet. If I figure it out I'll update here. In the meantime I've been opening up a private window.

@2TonWaffle, any sense which was the offending extension on your end?

**Comment by gabek** [comment]
To add to this thread, I've certainly seen cases now where loading the admin in Firefox requires a hard refresh. This only happens in Firefox.

**Comment by gabek** [comment]
This is still a thing sometimes, and I still don't know why. Still only with Firefox.

**Comment by gabek** [comment]
Closing as duplicate of https://github.com/owncast/owncast/issues/3097.
